name: Eduyacha CI/CD (backend)
run-name: Proceso de despliegue de Express API a Azure

on:
  push:
    branches: ["prod"]

jobs:
  # Compilar proyecto
  build-and-deploy:
    name: Compilar proyecto de Express y realizar despliegue
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            server

      - name: Crear ambiente con Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Instalar dependencias
        run: |
          npm install

      - name: Aplicar migraciones a db
        run: |
          npx prisma migrate deploy
          npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}

      - name: Compilar proyecto
        run: |
          npm run build

      - name: Listar archivos (source)
        run: ls -la

      - name: Preparar paquete de build/ para subida
        run: |
          mkdir -p build/prisma
          cp -r node_modules build
          cp -r prisma/* build/prisma/
          cp package.json build/

      - name: Listar archivos (build)
        run: |
          pwd
          ls -la build/

      # Despliegue del proyecto a Azure Webapp
      - name: Despliegue a Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: eduyacha
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./server/build

  tests:
    defaults:
      run:
        working-directory: "server"
    name: Realizar pruebas del proyecto (prod)
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            server

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Preparar env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          npm i
          npx prisma migrate deploy
          npx prisma generate

      - name: Realizar pruebas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          npm test
