# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Eduyacha CI/CD (backend)
run-name: Proceso de despliegue de Express API a Azure

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["prod"]

jobs:
  # Realizar las pruebas
  tests:
    name: Realizar pruebas del proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            server

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Realizar pruebas
        run: |
          npm i
          npm test

  # Compilar proyecto
  build:
    name: Compilar proyecto de Express
    needs: tests
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master
        with:
          sparse-checkout: |
            server

      - name: Crear ambiente con Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Compilar proyecto y módulos
        run: |
          npm install
          npm run build --if-present
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Listar archivos (source)
        run: ls -la

      - name: Preparar paquete de build/ para subida
        run: |
          mkdir -p build/prisma
          cp -r node_modules build
          cp -r prisma/* build/prisma/
          cp package.json build/

      - name: Listar archivos (build)
        run: ls -la build/

  # Despliegue del proyecto a Azure Webapp
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Despliegue a Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: eduyacha
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./server/build
