name: Eduyacha CI/CD (backend)
run-name: Suite de tests para el backend

on:
  push:
    branches: ["dev"]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  # Realizar pruebas
  tests:
    defaults:
      run:
        working-directory: server
    name: Realizar pruebas del proyecto (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Preparar env
        run: |
          npm i
          npx prisma migrate deploy
          npx prisma generate

      - name: Realizar pruebas
        run: |
          npm i
          npm test
