name: Eduyacha CI/CD (backend)
run-name: Suite de tests para el backend

on:
  push:
    branches: ["dev"]

jobs:
  # Realizar pruebas
  tests:
    defaults:
      run:
        working-directory: server
    name: Realizar pruebas del proyecto (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo de /server
        uses: actions/checkout@master

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Preparar env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          npm i
          npx prisma migrate deploy
          npx prisma generate

      - name: Realizar pruebas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: |
          npm i
          npm test
